### PR TITLE
fix(sops): what is this shit it doesn't exist

### PR DESCRIPTION
**Pull request by onedr0p**
only fools don't call collect

# 1-800-COLLECT

### CODE REVIEW

**Comment by onedr0p** [comment]
@JJGadgets I know you saw this

**Comment by JJGadgets** [comment]
yeah it does lol, it didn't work right until I added this

**Comment by JJGadgets** [comment]
also I been sleeping 😂

**Comment by onedr0p** [comment]
@JJGadgets Sleeping for 16 hours is not healthy 😏

No it does not...

https://www.github.com/getsops/sops/issues/982

**Comment by onedr0p** [comment]
Pls add to merge queue ❤️

**Comment by JJGadgets** [comment]
Alright enough teasing (and being lazy)

**Comment by kashalls** [comment]
https://github.com/user-attachments/assets/496171ec-7063-411e-8d24-0d2ee2f0ec23

**Pull request merged**
